name: summerkitchen
favicon: null
layout_spectrum: 0.90036
typography_spectrum: 0.2150980462320149
title: The Summer Kitchen Food Subscription Service
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7fbfe'
    - '#1126c8'
    - '#0c1002'
    - '#8f1b25'
    - '#b96135'
  brandStrength: 0.5
  lightness: 0.877293620724231
  saturation: 0.561483443249017
  rhythmicContrast: 0.6835798781830817
purpose: []
